alias bd := build-and-deploy

default:
	@just --list

# Run JBake in server mode
server:
	jbake -s

# Build site using JBake
build:
	jbake -b

# Deploy site to www.mrhaki.com
deploy:
	netlify deploy --dir=output --alias=mrhaki --prod --site=mrhaki

# Build site using JBake and deploy to www.mrhaki.com
build-and-deploy: build deploy

# Open Netlify Admin UI
admin:
	netlify open:admin

